### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by chfrank-cgn** [DezzardHD/InfluxDBv2Writer_GiraX1#1]
Hi DezzardHD,

this logic node is exactly what I was looking for!

Would you be open to publish a .zip package that can be imported into GPA?

Many thanks in advance and best regards:

Chris

**Comment by DezzardHD** [comment]
Hi Chris,

I‘ve puplished the logic-node in a KNX-Forum.
[http://service.knx-user-forum.de/?comm=download&id=20000080](http://service.knx-user-forum.de/?comm=download&id=20000080)

Feel free the sign up and download it from there. ^^
If this is not possible for you, I will consider uploading a .zip to GitHub.

Best regards

Moritz

**Comment by chfrank-cgn** [comment]
Hallo Moritz,

vielen Dank - hat funktioniert!

Viele Grüsse aus Köln,

Chris

________________________________________
