### ISSUE TITLE
InfluxDB Cloud needs HTTPS

### ISSUE THREAD

**Issue by chfrank-cgn** [DezzardHD/InfluxDBv2Writer_GiraX1#2]
Hi Moritz,

Great tool!

Unfortunately, InfluxDB Cloud needs HTTPS to connect - any chance you would be willing to update the writer to support this?

Thank you!

With best regards from Cologne,

Chris

**Comment by DezzardHD** [comment]
Hi Chris,

I'm currently trying to figure out how to write to InfluxDB Cloud.
I've created an account for the cloud version. The API expects a organization name. I wasn't able to find the organisation name in the user interface for the cloud. Do you know where to search?
I could try to use curl to execute a command on influxdb cloud to find out the name. But I hope there is an easier way. 

If the organization name is not easy to find I will use the orgID instead. For ease of use.

**Comment by DezzardHD** [comment]
Nevermind...
My mail address seems to be the organization name.
😅

**Comment by DezzardHD** [comment]
Hi Chris,
I modified the logic node so it should write data to InfluxDB Cloud.
At the moment I haven't published the node, cause I don't know if it works.

When I test the logic-node in Gira Project Assistant the simulation keeps no crashing as soon as I "activate" the logic-node (trying to send data).
I thought the problem resulted from HttpWebRequest, but testing in a separate program resulted succesfully sending data to InfluxDB.
Maybe it's just the simulation that is broke.

I'm not owning a Gira X1 so I'm not able to test the node on the actual hardware. Were you willing to help me out with this?
https://drive.google.com/file/d/1ME88t3rZM4qZ5mB0L8pMUMII90EbG2zQ/view?usp=sharing 

**!!! Consider that it might gonna crash. !!!**

**Comment by chfrank-cgn** [comment]
Hi Moritz,

sure - thank you! I'll try to test that today and let you know (I just combine the files into a zip archive to upload to GPA, right?)

Cheers: Chris

________________________________________

**Comment by DezzardHD** [comment]
Hi Chris,

nice!
You can download the whole ZIP archive. On the top right corner of google drive there‘s a button for downloading the whole file.
You will have to update the InfluxDBv2Writer in GPA and then configure it.
It‘s basically the same like with the old version.

There‘s a new field: InfluxDB Cloud URL
Type in your URL: something like this: https://us-west-2-1.aws.cloud2.influxdata.com

**Comment by DezzardHD** [comment]
Hey Chris,
it's me again.
Yesterday I somehow overlooked something really trivial.
It's working now in GPA simulation.

I'll update the logic node and upload the new version to the knx-user-forum.de.

I deactivated the google drive link. fyi

Best regards
Moritz

**Comment by chfrank-cgn** [comment]
Hi Moritz,

thanks a lot for your kind response! I can confirm the node works fine in GPA simulation mode (screenshot attached).

However, the node does not seem to send any data when running on the logic node. The logic engine status looks ok (attached) and in the engine log I think you can see that it is processing events (attached, the queue goes down), but there's no data arriving in the database.

I've set the log level to debug - should I see the connection attempts? Any other idea?

Thank you!

Cheers: Chris

PS: I've also attached the full set of log files, for now InfluxDB is the only node running there

________________________________________

**Comment by chfrank-cgn** [comment]
Hi Moritz,

I've enabled the HTTP Status output, and the logic status page (attached) shows a return code of 998 - which I think means "Unknown error" during POST.

Any idea where I should look? I've triple-checked the logic node's IP configuration and it looks absolutely fine to me.

Cheers: Chris

________________________________________
